# Generated by Django 2.1.3 on 2018-11-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem1_status', models.CharField(max_length=30)),
                ('problem2_status', models.CharField(max_length=30)),
                ('problem3_status', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
