# Generated by Django 2.1 on 2018-10-22 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='month',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savings',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
