# Generated by Django 2.1 on 2018-10-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181022_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='month',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='year',
        ),
    ]
