# Generated by Django 2.1 on 2018-10-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181022_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='month',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='year',
        ),
    ]
