# Generated by Django 2.1 on 2018-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('period', models.IntegerField()),
                ('type', models.BooleanField(default=False)),
                ('isFixed', models.IntegerField()),
            ],
        ),
    ]
