# Generated by Django 2.1 on 2018-10-23 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateField()),
                ('savings_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='concept',
            name='isFixed',
        ),
        migrations.AddField(
            model_name='concept',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='concept',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyinput',
            name='id_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Concept'),
        ),
        migrations.AddField(
            model_name='dailyinput',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
