# Generated by Django 2.1 on 2018-10-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181023_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinput',
            name='dummy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
