# Generated by Django 2.1 on 2018-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181006_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_concept', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateField()),
            ],
        ),
    ]
