# Generated by Django 2.1 on 2018-10-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dailyinput_dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='id_user',
            new_name='user',
        ),
    ]
