# Generated by Django 2.1 on 2018-10-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181023_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyinput',
            old_name='id_concept',
            new_name='concept',
        ),
        migrations.RenameField(
            model_name='dailyinput',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dailyinput',
            name='dummy',
        ),
    ]
