# Generated by Django 2.1 on 2018-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dailyinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
